function plot_rag_metrics(outputs_dir)
%PLOT_RAG_METRICS Plot synthetic enterprise RAG metrics generated by Python.
% Usage: plot_rag_metrics('outputs')

if nargin < 1
    outputs_dir = fullfile('..', 'outputs');
end
summary_path = fullfile(outputs_dir, 'results', 'synthetic_rag_summary.json');
if ~isfile(summary_path)
    error('Missing %s. Run scripts/run_synthetic_rag_lab.py first.', summary_path);
end
summary = jsondecode(fileread(summary_path));
labels = categorical({'Retrieval','Refusal','Access','Citation'});
values = [summary.retrieval_accuracy_on_answerable_queries, summary.refusal_accuracy, summary.access_control_correctness, summary.mean_citation_coverage];
figure('Color','w','Position',[100 100 820 430]);
bar(labels, values);
ylim([0 1.05]); grid on;
ylabel('Score');
title('Synthetic secure enterprise RAG control metrics');
exportgraphics(gcf, fullfile(outputs_dir, 'figures', 'synthetic_rag_metrics_matlab.png'), 'Resolution', 250);
end
